run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - gocyclo
    - dupl
    - unused
    - gosec
    - typecheck
    - revive
    - nolintlint

linters-settings:
  gocyclo:
    min-complexity: 15
  revive:
    confidence: 0.8
    severity: warning
  dupl:
    threshold: 100
  lll:
    line-length: 120
    tab-width: 1
  errcheck:
    check-type-assertions: true

exclude:
  - "should have comment.*or be unexported"
  - "error return value not checked.*(Close|Write|Flush)"