admin_token: access
postgres:
  connection_url: "postgres://postgres:1234@postgres:5432/document_manager"
redis:
  connection_url: "redis://redis:6379"
token_params:
  secret_key: access
  ttl_minutes: 60
